// components/SiteProfile/SiteProfile.tsx
import React from "react";
import Link from "next/link";
import TooltipIcon from "~/components/TooltipIcon";
import MdiIcon, { icons } from "~/components/icons/MdiIcon";
import { fullName, jobName, company, city, DEFAULT_LOCALE } from "~/data/SiteData";
import { profileSocialLinks } from "~/data/ProfileSocialsData";
import { t, getLocalePath } from "~/utils/i18n";
import "./SiteProfile.scss";

const IMAGE_HEIGHT = 35;
const IMAGE_WIDTH = 35;

export default function SiteProfile({ locale = DEFAULT_LOCALE }: { locale?: string }) {
  const author = fullName;

  return (
    <div id="profile-bio">
      <Link id="avatar-link" href={getLocalePath("/", locale)}>
        <img id="bio-avatar" src="/profile-picture.jpg" alt={author} width={105} height={100} />
      </Link>
      <div id="profile">
        <div id="bio">
          <div id="work">
            <MdiIcon path={icons.briefcase} />
            <span>
              {t(jobName, locale)}
              <br />
              {t("AT", locale)}
              {company}
            </span>
          </div>
          <div id="location">
            <MdiIcon path={icons.mapMarker} />
            <span>{city}</span>
          </div>
        </div>
        <div id="social-links">
          {profileSocialLinks.map((socialLink) => (
            <a
              key={socialLink.name}
              href={socialLink.link}
              target="_blank"
              rel="noopener noreferrer"
              className="social-link"
            >
              <TooltipIcon
                tooltip={socialLink.name}
                iconWidth={IMAGE_WIDTH}
                iconHeight={IMAGE_HEIGHT}
                iconPath={socialLink.imgPath}
                alt={socialLink.name.toLowerCase()}
              />
              <span>{t(socialLink.labelI18nCode, locale)}</span>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}

// components/SiteProfile.vue
<template>
  <div id="profile">
    <NuxtLink id="avatar-link" to="/">
      <NuxtImg id="bio-avatar" :width="400" :height="400" src="/profile-picture.jpg" :alt="author" />
    </NuxtLink>
    <div id="bio">
      <div id="work">
        <v-icon>{{ mdiBriefcase }}</v-icon>
        {{ $t(jobName) }} <br />
        {{ $t('AT') }}{{ company }}
      </div>
      <div id="location">
        <v-icon>{{ mdiMapMarker }}</v-icon>
        {{ city }}
      </div>
    </div>
    <div id="social-links">
      <a
        :href="socialLink.link"
        v-bind:key="socialLink.name"
        v-for="socialLink in profileSocialLinks"
        class="social-link"
      >
        <TooltipIcon
          :tooltip="socialLink.name"
          :iconWidth="IMAGE_WIDTH"
          :iconHeight="IMAGE_HEIGHT"
          :iconPath="socialLink.imgPath"
          :alt="socialLink.name.toLowerCase()"
        />
        <span>{{ $t(socialLink.labelI18nCode) }}</span>
      </a>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { mdiBriefcase, mdiMapMarker } from '@mdi/js';
import { fullName, jobName, company, city } from '~/data/SiteData';
import { profileSocialLinks } from '~/data/ProfileSocialsData';
const IMAGE_HEIGHT = 35;
const IMAGE_WIDTH = 35;

const author = fullName;
</script>

<style lang="scss">
#profile {
  display: flex;
  flex-direction: column;
  gap: 1.5em;

  #avatar-link {
    justify-content: center;
    display: flex;
  }

  #bio-avatar {
    height: 100px;
    width: 100px;
    border-radius: 50%;
    margin: 0 auto;
  }

  #bio {
    .v-icon {
      margin-right: 1rem;
    }

    > * {
      display: flex;
      flex-direction: row;
    }

    @media (width > 700px) {
      display: flex;
      flex-direction: column;
      row-gap: 0.5em;
      margin-left: 0.3em;
    }
  }

  #social-links {
    display: flex;
    flex-direction: column;
    gap: 2em 0.5em;
    font-size: 0.9rem;

    a {
      color: unset;
    }

    .social-link {
      display: flex;
      flex-direction: row;
      align-items: center;

      div {
        height: 35px;
        width: 35px;
      }

      img {
        border-radius: 50%;
      }

      span {
        margin-left: 1rem;
      }
    }
  }
}
</style>
