// pages/contact.vue
<template>
  <div>
    <NuxtLayout :titleCode="titleCode" :descriptionCode="descriptionCode">
      <div v-if="isMailSent">
        <p>{{ $t('EMAIL.SENT') }}</p>
      </div>

      <v-form id="contact-form" ref="contactForm" v-model="isValid" @submit.prevent="handleSubmit">
        <div id="contact-informations">
          <v-text-field
            id="name"
            class="form-field"
            v-model="name"
            :rules="[rules.length(5)]"
            :label="$t('NAME.FIRSTNAME')"
            hideDetails="auto"
            variant="outlined"
          ></v-text-field>

          <v-text-field
            id="email"
            type="email"
            class="form-field"
            v-model="email"
            :rules="[rules.email]"
            :label="$t('YOUR.EMAIL.ADDRESS')"
            hideDetails="auto"
            variant="outlined"
          ></v-text-field>
        </div>

        <v-textarea
          id="message"
          class="form-field"
          v-model="message"
          rows="8"
          :rules="[rules.length(10)]"
          :label="$t('MESSAGE')"
          hideDetails="auto"
          variant="outlined"
        ></v-textarea>

        <v-btn id="submit-button" type="submit" variant="flat" :disabled="!isValid">
          {{ $t('SEND') }}
        </v-btn>
      </v-form>
    </NuxtLayout>
  </div>
</template>

<script lang="ts" setup>
const titleCode = 'CONTACT.PAGE.TITLE';
const descriptionCode = 'CONTACT.PAGE.DESCRIPTION';
const isMailSent = ref(false);
const isValid = ref(false);
const name = ref('');
const email = ref('');
const message = ref('');

const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const rules = {
  email: (value: string) => !!(value || '').match(emailRegex) || 'Please enter a valid email',
  length: (len: number) => (value: string) => (value || '').length >= len || `Invalid character length, required ${len}`
};

function handleSubmit(e: any) {
  e.preventDefault();
  const data = new FormData(e.target);
  data.append('name', name.value);
  data.append('email', email.value);
  data.append('message', message.value);

  fetch('https://formspree.io/f/mkndgrkd', {
    method: 'POST',
    body: data,
    headers: { Accept: 'application/json' }
  })
    .then((response) => {
      if (response.ok) {
        isMailSent.value = true;
        e.target.reset();
        setTimeout(() => {
          isMailSent.value = false;
        }, 5000);
      }
    })
    .catch((error) => {
      console.error(error);
    });
}
</script>

<style lang="scss">
@import '../styles/colors.scss';

#contact-form {
  display: flex;
  flex-direction: column;
  gap: 3em;

  .v-field {
    background-color: #fff;
  }

  #contact-informations {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    column-gap: 3em;
  }

  .form-field {
    flex: 1;
  }

  #submit-button {
    margin: 0 auto;
  }
}

@media (width <= 700px) {
  #contact-form {
    width: 100%;

    #contact-informations {
      flex-direction: column;
      row-gap: 1em;
    }
  }
}
</style>

// src/pages/contact.tsx
import { useForm, ValidationError } from '@formspree/react';
import * as React from 'react';

import Box from '@mui/material/Box/Box';
import Button from '@mui/material/Button/Button';
import TextField from '@mui/material/TextField/TextField';
import { graphql } from 'gatsby';
import { useTranslation } from 'react-i18next';
import Layout from '../layout/Layout';
import { IPageProps } from '../model/IPageProps';
import { HeadComponent } from '../components/head/head';
import './page-styles/contact.scss';

const titleCode = 'CONTACT.PAGE.TITLE';
const descriptionCode = 'CONTACT.PAGE.DESCRIPTION';
const namespaceCode = 'contact';

export default function Contact(props: Readonly<IPageProps>): React.ReactElement {
  const [state, handleSubmit, reset] = useForm('mkndgrkd');

  const [nameText, setNameText] = React.useState('');
  const [emailText, setEmailText] = React.useState('');
  const [messageText, setMessageText] = React.useState('');

  const { t } = useTranslation();

  function isFormInvalid(): boolean {
    return state.submitting || !nameText.length || !emailText.length || !messageText.length;
  }

  return (
    <Layout titleCode={titleCode} descriptionCode={descriptionCode} location={props.location}>
      {state.succeeded ? (
        <div>
          <p>{t('EMAIL.SENT')}</p>
          <Button onClick={reset}>{t('SENT.ANOTHER.MAIL')}</Button>
        </div>
      ) : (
        <form onSubmit={handleSubmit}>
          <Box id="contact-form" component={'section'} gap={4}>
            <div id="contact-informations">
              <div className="form-field">
                <TextField
                  id="name"
                  type="text"
                  name="name"
                  className="contact-field"
                  label={t('NAME.FIRSTNAME')}
                  variant="outlined"
                  onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setNameText(event.target.value);
                  }}
                />
                <ValidationError className="error-message" prefix="Name" field="name" errors={state.errors} />
              </div>

              <div className="form-field">
                <TextField
                  id="email"
                  type="email"
                  name="email"
                  className="contact-field"
                  label={t('YOUR.EMAIL.ADDRESS')}
                  variant="outlined"
                  onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                    setEmailText(event.target.value);
                  }}
                />
                <ValidationError className="error-message" prefix="Email" field="email" errors={state.errors} />
              </div>
            </div>

            <div className="form-field">
              <TextField
                id="message"
                type="message"
                name="message"
                className="contact-field"
                label={t('MESSAGE')}
                multiline
                rows={8}
                onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
                  setMessageText(event.target.value);
                }}
              />
              <ValidationError className="error-message" prefix="Message" field="message" errors={state.errors} />
            </div>

            <Button id="submit-button" type="submit" disabled={isFormInvalid()} variant="contained">
              {t('SEND')}
            </Button>
          </Box>
        </form>
      )}
    </Layout>
  );
}

export const Head = ({ location, data, pageContext }) =>
  HeadComponent(location, data, pageContext, titleCode, descriptionCode, namespaceCode);

export const pageQuery = graphql`
  query ($language: String!) {
    locales: allLocale(filter: { language: { eq: $language } }) {
      edges {
        node {
          ns
          data
          language
        }
      }
    }
  }
`;
