// components/Bio.vue
<template>
  <div id="bio">
    <NuxtImg class="bio-avatar" :width="100" :height="100" src="/profile-picture.jpg" :alt="author" />
    <span>
      Écrit par <strong>{{ author }}</strong>
    </span>

    <div id="social-links-bio">
      <NuxtLink :to="linkedinLink">
        <TooltipIcon tooltip="LinkedIn" icon-path="/icons/socials/linkedin-icon.png" alt="linkedin" />
      </NuxtLink>
      <NuxtLink :to="githubLink">
        <TooltipIcon tooltip="Github" icon-path="/icons/socials/github-icon.png" alt="github" />
      </NuxtLink>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { fullName, linkedinLink, githubLink } from '~/data/SiteData';
const author = fullName;
</script>

<style lang="scss" scoped>
#bio {
  display: flex;
  flex-direction: column;
  row-gap: 0.8em;

  #social-links-bio {
    display: flex;
    flex-direction: row;
    column-gap: 0.5em;

    img {
      height: 30px;
    }
  }
}
</style>

// src/components/blog/bio/Bio.tsx
import Avatar from '@mui/material/Avatar/Avatar';
import Tooltip from '@mui/material/Tooltip/Tooltip';
import { graphql, useStaticQuery } from 'gatsby';
import { StaticImage } from 'gatsby-plugin-image';
import * as React from 'react';

import './Bio.scss';

export default function Bio(): React.ReactElement {
  const data = useStaticQuery(graphql`
    query BioQuery {
      site {
        siteMetadata {
          author
          job
          socials {
            linkedin
            github
          }
        }
      }
    }
  `);

  // Set these values by editing "siteMetadata" in gatsby-config.js
  const author = data.site.siteMetadata.author;
  const socials = data.site.siteMetadata.socials;
  const linkedinLink = socials.linkedin;
  const githubLink = socials.github;

  return (
    <div id="bio">
      <Avatar className="bio-avatar" alt={author} sx={{ width: 100, height: 100 }} src="/profile-picture.jpg" />
      <span>
        Écrit par <strong>{author}</strong>
      </span>
      <div id="social-links-bio">
        <Tooltip title="LinkedIn">
          <a href={linkedinLink}>
            <StaticImage src="../../../images/icons/linkedin-icon.png" alt="linkedin" />
          </a>
        </Tooltip>

        <a href={githubLink}>
          <Tooltip title="Github">
            <div>
              <StaticImage src="../../../images/icons/github-icon.png" alt="github" />
            </div>
          </Tooltip>
        </a>
      </div>
    </div>
  );
}
