// components/TemplateBlogPost.vue
<template>
  <article class="blog-post" itemScope itemType="https://schema.org/Article">
    <header>
      <h1 itemProp="headline">{{ doc.title }}</h1>
      <p>{{ format(doc.date, "dd MMMM yyyy", { locale: getLocaleFromLanguage(locale) }) }}</p>
      {{ doc.description }}
    </header>
    <p>
      <NuxtImg class="article-illustration" :src="blogUrlPrefix + doc.image" :width="600" alt="Illustration article" />
      <em v-html="doc.imageSubtitle" />
    </p>
    <section itemProp="articleBody">
      <ContentRenderer :value="doc" />
    </section>
    <hr />
    <footer class="blog-post-footer">
      <Bio />
      <div class="share-article-container">
        <span>Partager cet article :</span>
        <div id="share-buttons">
          <v-no-ssr>
            <a href="#" @click="handleShare(`${facebookShareUrl}${doc.path}`)">
              <v-tooltip text="Partager sur Facebook" location="top">
                <template #activator="{ props }">
                  <v-icon v-bind="props">{{ mdiFacebook }}</v-icon>
                </template>
              </v-tooltip>
            </a>

            <a href="#" @click="handleShare(`${twitterShareUrl}${doc.path}`)">
              <v-tooltip text="Partager sur X" location="top">
                <template #activator="{ props }">
                  <v-icon v-bind="props">{{ mdiTwitter }}</v-icon>
                </template>
              </v-tooltip>
            </a>

            <a href="#" @click="handleShare(`${linkedinShareUrl}${doc.path}`)">
              <v-tooltip text="Partager sur LinkedIn" location="top">
                <template #activator="{ props }">
                  <v-icon v-bind="props">{{ mdiLinkedin }}</v-icon>
                </template>
              </v-tooltip>
            </a>
          </v-no-ssr>
        </div>
      </div>
    </footer>
  </article>

  <nav class="blog-post-nav">
    <ul>
      <li>
        <NuxtLink v-if="previous?.path" :to="localePath(previous.path)" rel="prev"> ← {{ previous.title }} </NuxtLink>
      </li>
      <li>
        <NuxtLink v-if="next?.path" :to="localePath(next.path)" rel="next"> {{ next.title }} → </NuxtLink>
      </li>
    </ul>
  </nav>
</template>

<script lang="ts" setup>
import { format } from "date-fns";
import { mdiFacebook, mdiTwitter, mdiLinkedin } from "@mdi/js";
import { getLocaleFromLanguage } from "~/utils/DateUtils";
import type { Collections, ContentNavigationItem } from "@nuxt/content";

defineProps<{
  doc: Collections["blog"];
  previous?: ContentNavigationItem | null;
  next?: ContentNavigationItem | null;
}>();

const { locale } = useI18n();
const localePath = useLocalePath();

const blogUrlPrefix = "/blog/";

const facebookShareUrl = "https://www.facebook.com/sharer.php?u=";
const twitterShareUrl = "https://twitter.com/share?url=";
const linkedinShareUrl = "https://www.linkedin.com/shareArticle?url=";

function handleShare(url: string): void {
  window.open(encodeURI(url), "", "menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=400,width=700");
}
</script>

<style lang="scss">
.blog-post {
  .article-illustration {
    margin: 1em auto 0.5em;
  }

  ul {
    list-style: disc;
  }

  ol {
    list-style: decimal;
  }

  img {
    display: flex;
    margin: 0.2em auto;
  }

  img + em {
    display: inline-block;
    font-size: 0.8rem;
    color: #4b4545;
    margin-top: 0.2em;
    width: 100%;
    text-align: center;
    white-space: pre-line;
  }

  .blog-post-footer {
    display: flex;
    flex-direction: row;
    justify-content: space-between;

    .share-article-container {
      display: flex;
      flex-direction: row;
      align-content: center;
      flex: 0 1 60%;
      align-items: baseline;
      margin-right: 1em;

      #share-buttons {
        display: flex;
        flex-direction: row;
      }

      svg {
        height: 37px;
        width: 37px;
      }
    }
  }
}

.blog-post-nav {
  ul {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    list-style: none;
    padding: 0;
  }
}

@media (width >= 950px) {
  article {
    img {
      max-width: 600px;
      max-height: 500px;
    }
  }
}

@media (width<= 600px) {
  .blog-post {
    .blog-post-footer {
      .share-article-container {
        flex-direction: column;
      }
    }
  }
}
</style>

// src/components/TemplateBlogPost/TemplateBlogPost.tsx
"use client";

import React from "react";
import Link from "next/link";
import { format } from "date-fns";
import Bio from "~/components/Bio/Bio";
import Facebook from "@mui/icons-material/Facebook";
import Twitter from "@mui/icons-material/Twitter";
import LinkedIn from "@mui/icons-material/LinkedIn";
import { getLocaleFromLanguage } from "~/utils/DateUtils";
import { getLocalePath } from "~/utils/i18n";
import type { BlogPost } from "~/utils/content";
import { DEFAULT_LOCALE } from "~/data/SiteData";
import "./TemplateBlogPost.scss";

interface TemplateBlogPostProps {
  doc: BlogPost;
  previous?: BlogPost | null;
  next?: BlogPost | null;
  locale?: string;
}

export default function TemplateBlogPost({ doc, previous, next, locale = DEFAULT_LOCALE }: TemplateBlogPostProps) {
  const blogUrlPrefix = "/blog/";
  const facebookShareUrl = "https://www.facebook.com/sharer.php?u=";
  const twitterShareUrl = "https://twitter.com/share?url=";
  const linkedinShareUrl = "https://www.linkedin.com/shareArticle?url=";

  const handleShare = (url: string, e: React.MouseEvent) => {
    e.preventDefault();
    window.open(encodeURI(url), "", "menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=400,width=700");
  };

  const formattedDate = doc.date
    ? format(new Date(doc.date), "dd MMMM yyyy", {
        locale: getLocaleFromLanguage(locale)
      })
    : "";

  return (
    <>
      <article className="blog-post" itemScope itemType="https://schema.org/Article">
        <header>
          <h1 itemProp="headline">{doc.title}</h1>
          <p>{formattedDate}</p>
          {doc.description}
        </header>
        <p>
          <img
            className="article-illustration"
            src={`${blogUrlPrefix}${doc.image}`}
            width={600}
            alt="Illustration article"
          />
          {doc.imageSubtitle && <em dangerouslySetInnerHTML={{ __html: doc.imageSubtitle }} />}
        </p>
        <section itemProp="articleBody" dangerouslySetInnerHTML={{ __html: doc.html }} />
        <hr />
        <footer className="blog-post-footer">
          <Bio />
          <div className="share-article-container">
            <span>Partager cet article :</span>
            <div id="share-buttons">
              <a
                href="#"
                title="Partager sur Facebook"
                onClick={(e) => handleShare(`${facebookShareUrl}https://arnaudflaesch.github.io${doc.path}`, e)}
              >
                <Facebook />
              </a>

              <a
                href="#"
                title="Partager sur X"
                onClick={(e) => handleShare(`${twitterShareUrl}https://arnaudflaesch.github.io${doc.path}`, e)}
              >
                <Twitter />
              </a>

              <a
                href="#"
                title="Partager sur LinkedIn"
                onClick={(e) => handleShare(`${linkedinShareUrl}https://arnaudflaesch.github.io${doc.path}`, e)}
              >
                <LinkedIn />
              </a>
            </div>
          </div>
        </footer>
      </article>

      <nav className="blog-post-nav">
        <ul>
          <li>
            {previous?.path && (
              <Link href={getLocalePath(previous.path, locale)} rel="prev">
                ← {previous.title}
              </Link>
            )}
          </li>
          <li>
            {next?.path && (
              <Link href={getLocalePath(next.path, locale)} rel="next">
                {next.title} →
              </Link>
            )}
          </li>
        </ul>
      </nav>
    </>
  );
}
