// src/pages/cv.tsx
import './page-styles/cv.scss';

import { Button, Tooltip } from '@mui/material';
import { format } from 'date-fns';
import { graphql } from 'gatsby';
import { StaticImage } from 'gatsby-plugin-image';
import { useI18next, useTranslation } from 'gatsby-plugin-react-i18next';
import * as React from 'react';
import { ReactElement } from 'react';
import { PhotoProvider, PhotoView } from 'react-photo-view';
import Seo from '../components/Seo';
import Experience from '../components/cv/experience/Experience';
import Skills from '../components/cv/skills/Skills';
import DetailBlock from '../components/detailBlock/DetailBlock';
import formationData from '../data/EducationData';
import { hobbiesList } from '../data/HobbiesData';
import jobData from '../data/WorkData';
import Layout from '../layout/Layout';
import { IPageProps } from '../model/IPageProps';
import { ITranslatableElement } from '../model/ITranslatableElement';
import { getLocaleFromLanguage } from '../utils/DateUtils';
import { getTranslation } from '../utils/TranslationUtils';

const titleCode = 'CV.PAGE.TITLE';
const descriptionCode = 'CV.PAGE.DESCRIPTION';
const namespaceCode = 'cv';

export default function CV(props: Readonly<IPageProps>): ReactElement {
  const scrumOrgLink = props.data.site.siteMetadata.socials.scrumOrg;
  const githubActionsBadgeLink = 'https://www.credly.com/badges/bcc83162-8396-4e95-b73d-b89ad2658027';
  const githubAdvancedSecurityBadgeLink = 'https://www.credly.com/badges/a20775eb-8713-4013-b0fe-d5e359a543e8';

  const DEFAUL_NUMBER_OF_JOBS_TO_SHOW = 3;

  const { t } = useTranslation();
  const { language } = useI18next();

  const [jobIndexEnd, setJobIndexEnd] = React.useState<number | undefined>(DEFAUL_NUMBER_OF_JOBS_TO_SHOW);

  function showMoreJobs() {
    setJobIndexEnd(undefined);
  }

  function showLessJobs() {
    setJobIndexEnd(DEFAUL_NUMBER_OF_JOBS_TO_SHOW);
  }

  function createDetailBlock(title: string, detail: string): ReactElement {
    return <DetailBlock key={title} titleComponent={<h3>{title}</h3>} detailComponent={<div>{detail}</div>} />;
  }

  return (
    <Layout titleCode={titleCode} descriptionCode={descriptionCode} location={props.location}>
      <div id="cv-page">
        <div id="job-list">
          <div id="jobs-header">
            <h2>{t('WORK.EXPERIENCE')}</h2>
            <Button
              id="cv-download-button"
              href={language === 'fr' ? '/CV.pdf' : '/Resume.pdf'}
              variant="contained"
              download={`${t('RESUME')} Arnaud Flaesch.pdf`}
            >
              {t('DOWNLOAD.RESUME')}
            </Button>
          </div>
          {jobData.slice(0, jobIndexEnd).map((job) => (
            <Experience key={job.name} {...job} />
          ))}

          {jobIndexEnd === DEFAUL_NUMBER_OF_JOBS_TO_SHOW && (
            <Button onClick={showMoreJobs}>{t('SEE.MORE.EXPERIENCES')}</Button>
          )}
          {jobIndexEnd !== DEFAUL_NUMBER_OF_JOBS_TO_SHOW && (
            <Button onClick={showLessJobs}>{t('SEE.LESS.EXPERIENCES')}</Button>
          )}
        </div>

        <div id="certifications-list">
          <DetailBlock
            titleComponent={<h3>{'Certifications'}</h3>}
            detailComponent={
              <div id="certifications-detail-list">
                <div>
                  <h4>
                    Professional Scrum Master 1 {t('AND')} 2 -{' '}
                    {format(new Date(2023, 11, 1), 'MMMM yyyy', { locale: getLocaleFromLanguage(language) })}
                  </h4>
                  <div className="certifications-logos">
                    <Tooltip title="PSM 1">
                      <a href={scrumOrgLink}>
                        <StaticImage width={80} src="../images/certifications/psm1.png" alt={'PSM 1'} />
                      </a>
                    </Tooltip>
                    <Tooltip title="PSM 2">
                      <a href={scrumOrgLink}>
                        <StaticImage width={80} src="../images/certifications/psm2.png" alt={'PSM 2'} />
                      </a>
                    </Tooltip>
                  </div>
                </div>

                <hr />

                <div>
                  <h4>
                    GitHub Advanced Security {t('AND')} Actions -{' '}
                    {format(new Date(2024, 2, 1), 'MMMM yyyy', { locale: getLocaleFromLanguage(language) })}
                  </h4>
                  <div className="certifications-logos">
                    <Tooltip title="GitHub Actions">
                      <a href={githubActionsBadgeLink}>
                        <StaticImage
                          width={100}
                          src="../images/certifications/github-actions.png"
                          alt={'GitHub Actions'}
                        />
                      </a>
                    </Tooltip>
                    <Tooltip title="GitHub Advanced Security">
                      <a href={githubAdvancedSecurityBadgeLink}>
                        <StaticImage
                          width={100}
                          src="../images/certifications/github-advanced-security.png"
                          alt={'GitHub Advanced Security'}
                        />
                      </a>
                    </Tooltip>
                  </div>
                </div>

                <hr />

                <div>
                  <h4>
                    {t('SUSTAINABLE.IT.KNOWLEDGE.CERTIFICATE')} -{' '}
                    {format(new Date(2024, 3, 1), 'MMMM yyyy', { locale: getLocaleFromLanguage(language) })}
                  </h4>
                  <PhotoProvider>
                    <PhotoView src="/certifications/numerique-responsable.png">
                      <Tooltip title={t('SUSTAINABLE.IT.KNOWLEDGE.CERTIFICATE')}>
                        <img className="large-image"
                          src="/certifications/numerique-responsable.png"
                          alt={t('SUSTAINABLE.IT.KNOWLEDGE.CERTIFICATE') ?? ''}
                        />
                      </Tooltip>
                    </PhotoView>
                  </PhotoProvider>
                </div>
              </div>
            }
          />
        </div>

        <div id="formation-list">
          <h2>{t('EDUCATION')}</h2>
          {formationData.map((formation) => (
            <Experience key={formation.title_fr} {...formation} />
          ))}
        </div>

        <h2 id="skills-title">{t('LANGUAGES.TOOLS')}</h2>
        <Skills />

        <h2 id="hobbies-title">{t('HOBBIES')}</h2>

        <div id="hobbies-list">
          {hobbiesList.map((hobby) =>
            createDetailBlock(
              hobby[language as keyof ITranslatableElement].title,
              hobby[language as keyof ITranslatableElement].description
            )
          )}
        </div>
      </div>
    </Layout>
  );
}

export const Head = ({ location, data, pageContext }) => {
  const translatedTitle = getTranslation(titleCode, pageContext.language, namespaceCode, data.locales.edges);
  const translatedDescription = getTranslation(
    descriptionCode,
    pageContext.language,
    namespaceCode,
    data.locales.edges
  );
  return (
    <Seo
      location={location.pathname}
      translatedTitle={translatedTitle}
      translatedDescription={translatedDescription}
      language={pageContext.language}
    />
  );
};

export const pageQuery = graphql`
  query ($language: String!) {
    site {
      siteMetadata {
        socials {
          scrumOrg
        }
      }
    }
    locales: allLocale(filter: { language: { eq: $language } }) {
      edges {
        node {
          ns
          data
          language
        }
      }
    }
  }
`;

// pages/cv.vue
<template>
  <div class="layout-container">
    <NuxtLayout :titleCode="titleCode" :descriptionCode="descriptionCode">
      <div id="cv-page">
        <div id="job-list">
          <div id="jobs-header">
            <h2>{{ $t('WORK.EXPERIENCE') }}</h2>
            <a
              id="cv-download-button"
              :href="locale === DEFAULT_LOCALE ? '/CV.pdf' : '/Resume.pdf'"
              color="primary"
              :download="`${$t('RESUME')} Arnaud Flaesch.pdf`"
              ><v-btn variant="flat" color="primary">
                {{ $t('DOWNLOAD.RESUME') }}
              </v-btn></a
            >
          </div>
          <Experience v-for="(job, index) in jobData" :key="job.name" :experience="job" :style="isVisible(index)" />

          <v-btn
            v-if="jobIndexEnd === DEFAULT_NUMBER_OF_JOBS_TO_SHOW"
            class="cv-button"
            color="primary"
            @click="() => (jobIndexEnd = undefined)"
          >
            {{ $t('SEE.MORE.EXPERIENCES') }}
          </v-btn>
          <v-btn v-else color="primary" class="cv-button" @click="() => (jobIndexEnd = DEFAULT_NUMBER_OF_JOBS_TO_SHOW)">
            {{ $t('SEE.LESS.EXPERIENCES') }}
          </v-btn>
        </div>

        <Certifications />

        <div id="formation-list">
          <h2>{{ $t('EDUCATION') }}</h2>
          <Experience v-for="formation in formationData" :key="formation.title_fr" :experience="formation" />
        </div>

        <h2 id="skills-title">{{ $t('LANGUAGES.TOOLS') }}</h2>
        <Skills />

        <h2 id="hobbies-title">{{ $t('HOBBIES') }}</h2>

        <div id="hobbies-list">
          <DetailBlock v-for="(hobby, index) in hobbiesList" :key="index">
            <template #titleComponent
              ><h3>{{ hobby[locale as keyof ITranslatableElement].title }}</h3>
            </template>
            <template #detailComponent> {{ hobby[locale as keyof ITranslatableElement].description }} </template>
          </DetailBlock>
        </div>
      </div>
    </NuxtLayout>
  </div>
</template>

<script lang="ts" setup>
import { formationData } from '~/data/EducationData';
import { jobData } from '~/data/WorkData';
import { hobbiesList } from '~/data/HobbiesData';
import type { ITranslatableElement } from '~/model/ITranslatableElement';
import { ref, type Ref } from 'vue';
import { DEFAULT_LOCALE } from '../data/SiteData';
import { useI18n } from 'vue-i18n';

const DEFAULT_NUMBER_OF_JOBS_TO_SHOW = 3;

const { locale } = useI18n();
const jobIndexEnd: Ref<number | undefined> = ref(DEFAULT_NUMBER_OF_JOBS_TO_SHOW);

const titleCode = 'CV.PAGE.TITLE';
const descriptionCode = 'CV.PAGE.DESCRIPTION';

function isVisible(index: number) {
  if (!jobIndexEnd.value || (jobIndexEnd.value && index < jobIndexEnd.value)) {
    return { display: 'inherit' };
  } else {
    return { display: 'none' };
  }
}
</script>

<style lang="scss" scoped>
#cv-page {
  display: flex;
  flex-direction: column;
  row-gap: 2em;

  #jobs-header {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    flex-wrap: wrap;
  }

  .cv-button {
    margin: 0 auto;
  }

  #job-list,
  #formation-list,
  #hobbies-list {
    display: flex;
    flex-direction: column;
    row-gap: 0.5em;
  }
}
</style>
